name: 'Cert Update for Tencent Cloud'
description: 'Update SSL certificates for multiple Tencent Cloud products, including CDN, API Gateway and CLB'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  secret_id:
    description: 'Tencent cloud secret id. Should be referred to a encrypted environment variable'
    required: true
  secret_key:
    description: 'Tencent cloud secret key. Should be referred to a encrypted environment variable'
    required: true
  cloud_service_type:
    description: 'The cloud service type you want to update certificate for. Supported values: cdn, clb, apigateway'
    required: true

  path_certificate:
    description: 'File path of the certificate. '
    required: true
  path_private_key:
    description: 'File path of the private key. '
    required: true

  region:
    description: 'Tencent cloud service region. Required when cloud_service_type is apigateway, clb'
    required: false
  domain:
    description: 'Domain name for which to update SSL certificate'
    required: false
  apigw_service_id:
    description: 'API Gateway service id, required when cloud_service_type is apigateway'
    required: false
  clb_id:
    description: 'The ID of the CLB, required when cloud_service_type is clb'
    required: false
  clb_port:
    description: 'The port of the CLB, required when cloud_service_type is clb'
    required: false
  clb_protocol:
    description: 'The protocol of the CLB, required when cloud_service_type is clb'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'