name: 'Cert Update for Tencent Cloud'
description: 'Update SSL certificates for multiple Tencent Cloud products, including CDN, API Gateway and CLB'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  secret_id:
    description: 'Tencent cloud secret id. Should be referred to a encrypted environment variable'
    required: true
  secret_key:
    description: 'Tencent cloud secret key. Should be referred to a encrypted environment variable'
    required: true
  cloud_service_type:
    description: 'The cloud service type you want to update certificate for. Supported values: cdn, apigateway'
    required: true

  domain_name:
    description: 'Domain name for which to update SSL certificate'
    required: false
  path_certificate:
    description: 'File path of the certificate. Should be referred to a encrypted environment variable'
    required: true
  path_private_key:
    description: 'File path of the private key. Should be referred to a encrypted environment variable'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'